### PR TITLE
bn-getting-started-page

### PR DESCRIPTION
**Pull request by jamal-pb95**

### CODE REVIEW

**Comment by jamal-pb95** [comment]
@shakib609 please see my new PR

**Comment by shakib609** [comment]
`Files Changed`: **2** ?

**Comment by jamal-pb95** [comment]
yes, I have committed `.gitignore` to ignore my `.vscode` setup changes. is it not permissible?

**Comment by shakib609** [comment]
> yes, I have committed `.gitignore` to ignore my `.vscode` setup changes. is it not permissible?

I don't think so.

**Comment by nutboltu** [comment]
@jamal-pb95 I know it's completely make sense to add `.vscode` in the `.gitignore`. But Let's not modify any other file except the readme files.

**Comment by jamal-pb95** [comment]
Thanks, @nutboltu and what is the next step? Are you going to merge my changes or I can make another PR with just single file change?

**Comment by nutboltu** [comment]
@jamal-pb95 You can revert the file changes in a different commit. Then we will merge it to master. We don't need to open a new PR for this.

**Comment by jamal-pb95** [comment]
Sorry @nutboltu for all of my mistakes. I have raised another PR [#33](https://github.com/reactjs/bn.reactjs.org/pull/33) and gonna close this one. Please review and merge my new PR[#33](https://github.com/reactjs/bn.reactjs.org/pull/33). Thanks for your time and consideration.

**Pull request closed without merging**
