### PR TITLE
Translated and polished thinking-in-react page full

### PR DESCRIPTION
**Pull request by nafistiham**
This is my first pull in this repo. I have read some of the translations and tried to translate the page accordingly. Some mentionable points are stated hereby:

1. I have used some bracketed English words for clarification after some that cannot be or should not be translated.
2. Broken apart some sentences for further clarification.
3. I added a few lines for more direct interaction with the reader.
4. Tried to be as straight forward as possible with the actual text.

Please review my PR and let me know if some changes need to be reverted or polished even more.

### CODE REVIEW

**Comment by nafistiham** [comment]
@shakib609 vai, I did not actually add extra 'lines' rather sentences basically breaking complex and compound sentences in simple ones. The difference between added and redacted lines is so high because I have contributed in this project from two different machines and did a copy paste once from another machine once. You'll see the some lines don't match. I will try to avoid this problem from later on by not breaking the sequence in the .MD file. But, I believe the translation is quite similar to the English one. 
I apologize for this inconvenience.

**Comment by shakib609** [comment]
> @shakib609 vai, I did not actually add extra 'lines' rather sentences basically breaking complex and compound sentences in simple ones. The difference between added and redacted lines is so high because I have contributed in this project from two different machines and did a copy paste once from another machine once. You'll see the some lines don't match. I will try to avoid this problem from later on by not breaking the sequence in the .MD file. But, I believe the translation is quite similar to the English one.
> I apologize for this inconvenience.

I really appreciate your effort and the time you have put to translate this documentation. But there are a few reasons as to why we have to follow this rule.
- This makes the code review process much more convenient
- `reactjs-translation-bot` updates this repository when anything is updated in the main repository. When it has to update an already translated file, it raises a **Merge Conflict** for the lines that got updated. This makes the process of updating the translation according to the updated docs easier.

As far as I know, it is not prohibited to break up complex/compound sentences into simple sentences. You can do that without adding new lines. If you are having problems with the line length. You can easily overcome that by enabling wrapping in your editor.

**Comment by nafistiham** [comment]
I believe I have found out all the extra lines which might have been added because of the copy-paste. Should I edit the file again to match added and redacted lines and commit again?

Also, now I am editing every English line to be translated into Bangla. Not deleting or adding any new line. I think this will solve the problem.

**Comment by shakib609** [comment]
> I believe I have found out all the extra lines which might have been added because of the copy-paste. Should I edit the file again to match added and redacted lines and commit again?
> 
> Also, now I am editing every English line to be translated into Bangla. Not deleting or adding any new line. I think this will solve the problem.

@nafistiham you are doing great. Yes, please edit and update `thinking-in-react` page. And also, I have noticed that you are pushing translations of other pages to this PR. This is not really prohibited but I think your translations would be reviewed and merged by the maintainers much sooner if they are separate. So, please keep that in mind.

I'll try to give my review ASAP.
Cheers and keep up the good work. :v:

**Comment by nafistiham** [comment]
Thanks a lot. I hope I will be making fewer mistakes from now on. 
I will be committing the other pages in new PRs and also edit the thinking-in-react page first.

**Comment by nutboltu** [comment]
@nafistiham very good start. I would recommend to create separate PR for each page. It would be easy to review and track down the work.

**Comment by nafistiham** [comment]
Thanks a lot for the appreciation.
As I haven't had hands-on experience in collaborating in a 'so many contributors' project, I am not an expert in managing multiple branches yet. My goal is to keep different file commits in different branches and creating pull requests for each file separately. But, I haven't yet found out a good way to do that. When I create a branch, all the changes are already done in all the files. I am definitely missing something. I will sort this out soon and get back to you.

**Comment by nafistiham** [comment]
> 
> 
> Thanks a lot for the appreciation.
> As I haven't had hands-on experience in collaborating in a 'so many contributors' project, I am not an expert in managing multiple branches yet. My goal is to keep different file commits in different branches and creating pull requests for each file separately. But, I haven't yet found out a good way to do that. When I create a branch, all the changes are already done in all the files. I am definitely missing something. I will sort this out soon and get back to you.

As far as I have studied, I made a huge mishap by committing these changes to the master branch itself. So, I will wait until these three files are merged successfully. Till then, I will version control my other files myself, without committing any more. If and when these pages are done, I will PR for other pages. Please take your time reviewing. Apologies for this inconvenience.

**Comment by nafistiham** [comment]
I guess I am done with the three files `thinking-in-react`, `components-and-props`, and `reference-react`

- The components and props page doesn't have its title translated. Please see to that. Didn't put an extra commit for that only. Can do that if needed. 

- I have diff compared all the files with the English doc, in vs code and they show no anomaly, but somehow, there is a line gap in the components and props file and a merge conflict in the thinking in react file. Maybe because my master is 5 commits behind the actual master branch. I think people with write access can easily resolve this.

- As I have said, I am not going to (shouldn't) put another pull request or commit as long as these three files are still in review. But, I will keep translating the pages and inform them in the comment thread.

- I have tried to go as close as possible to the actual doc. But, on the API page, the language is pretty tricky. So I broke the lines into several parts and tried to maintain the readability of Bangla language with the correct meanings intended. As I don't have the in-depth knowledge of all these APIs, I might have slipped here and there. Please see to that.

Looking forward to the merge. Thanks in advance.

**Comment by nutboltu** [comment]
@nafistiham, Thanks for your all hard works. As far as I understand you made all your changes in your fork master branch.  I would suggest to create a new branch with one page changes and also close this PR. If you need any help regarding this process please let me know.

**Comment by nafistiham** [comment]
@nutboltu vai, the problem I am facing is, when I create another branch, the new branch is similar to my master branch. So if I try to PR from that one, all the unmerged changes in my master are pushed again. So I propose doing thus:

1. Close my PR.
2. Create another branch.
3. Replace all the files from the master branch of bn.react.org to my new branch.
4. Start committing from exactly one file from that branch.

I have consulted this problem with others, and I have been suggested to start anew. As my master branch is already corrupted from the actual master branch.

**Comment by shakib609** [comment]
@nafistiham you can keep your fork updated easily.
```
$ git remote add upstream https://github.com/reactjs/bn.reactjs.org.git    
```
Now, everytime before creating a new branch and starting your translation run this command:
```
$ git fetch upstream master
```
This will update your master branch with the latest changes. After that, create a new branch and start making necessary changes.

**Comment by nafistiham** [comment]
I have tried doing that, but there show some merge conflicts which might take some time to fix. I am finally deleting my fork and closing this PR.

**Pull request closed without merging**
